apiVersion: v2
name: pgbouncer
description: A Helm chart for deploying PgBouncer, a PostgreSQL connection pooler,
  on Kubernetes
home: https://github.com/degauden/pgbouncer
keywords:
- pgbouncer
- postgresql
- kubernetes
kubeVersion: '>= 1.31.0-0'
maintainers:
- email: Hubert.Degaudenzi@gmail.com
  name: Hubert Degaudenzi
  url: https://github.com/degauden
type: application
version: 0.1.0
appVersion: "0.3.0"
